version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_USER: "robel"
      DB_NAME: "message_db"
      DB_PASSWORD: "123"
      DB_HOST: 'db'
      DB_PORT: '3306'
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'robel'
      MYSQL_PASSWORD: "123"
      MYSQL_DB: 'message_db'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
