CREATE DATABASE IF NOT EXISTS message_db;
/*CREATE USER 'robel'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'robel'@'%' WITH GRANT OPTION;
USE message_db;

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender VARCHAR(255) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
*/
